
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct _int3
    {
        public _int3(ByteBuf _buf)
        {
            X = _buf.ReadInt();
            Y = _buf.ReadInt();
            Z = _buf.ReadInt();

            PostInit();
        }

        public static _int3 Deserialize_int3(ByteBuf _buf)
        {
            return new _int3(_buf);
        }

        public readonly int X;

        public readonly int Y;

        public readonly int Z;



        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "z:" + Z + ","
            + "}";
        }

        partial void PostInit();
    }
}
