
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct _int4
    {
        public _int4(ByteBuf _buf)
        {
            X = _buf.ReadInt();
            Y = _buf.ReadInt();
            Z = _buf.ReadInt();
            W = _buf.ReadInt();

            PostInit();
        }

        public static _int4 Deserialize_int4(ByteBuf _buf)
        {
            return new _int4(_buf);
        }

        public readonly int X;

        public readonly int Y;

        public readonly int Z;

        public readonly int W;



        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "z:" + Z + ","
            + "w:" + W + ","
            + "}";
        }

        partial void PostInit();
    }
}
