
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct _int2
    {
        public _int2(ByteBuf _buf)
        {
            X = _buf.ReadInt();
            Y = _buf.ReadInt();

            PostInit();
        }

        public static _int2 Deserialize_int2(ByteBuf _buf)
        {
            return new _int2(_buf);
        }

        public readonly int X;

        public readonly int Y;



        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "}";
        }

        partial void PostInit();
    }
}
