
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BlockCellConfigCategory : Singleton<BlockCellConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BlockCellConfig> _dataMap;
        private readonly List<BlockCellConfig> _dataList;

        public BlockCellConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BlockCellConfig>();
            _dataList = new List<BlockCellConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BlockCellConfig _v;
                _v = BlockCellConfig.DeserializeBlockCellConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.ID, _v);
            }

            PostInit();
        }

        public Dictionary<int, BlockCellConfig> DataMap => _dataMap;
        public List<BlockCellConfig> DataList => _dataList;

        public BlockCellConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BlockCellConfig Get(int key) => _dataMap[key];
        public BlockCellConfig this[int key] => _dataMap[key];
        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
