
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BlockSceneConfigCategory : Singleton<BlockSceneConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BlockSceneConfig> _dataMap;
        private readonly List<BlockSceneConfig> _dataList;

        public BlockSceneConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BlockSceneConfig>();
            _dataList = new List<BlockSceneConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BlockSceneConfig _v;
                _v = BlockSceneConfig.DeserializeBlockSceneConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.ID, _v);
            }

            PostInit();
        }

        public Dictionary<int, BlockSceneConfig> DataMap => _dataMap;
        public List<BlockSceneConfig> DataList => _dataList;

        public BlockSceneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BlockSceneConfig Get(int key) => _dataMap[key];
        public BlockSceneConfig this[int key] => _dataMap[key];
        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
