
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BlockItemConfigCategory : Singleton<BlockItemConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BlockItemConfig> _dataMap;
        private readonly List<BlockItemConfig> _dataList;

        public BlockItemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BlockItemConfig>();
            _dataList = new List<BlockItemConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BlockItemConfig _v;
                _v = BlockItemConfig.DeserializeBlockItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.ID, _v);
            }

            PostInit();
        }

        public Dictionary<int, BlockItemConfig> DataMap => _dataMap;
        public List<BlockItemConfig> DataList => _dataList;

        public BlockItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BlockItemConfig Get(int key) => _dataMap[key];
        public BlockItemConfig this[int key] => _dataMap[key];
        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
