
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BlockLevelConfigCategory : Singleton<BlockLevelConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BlockLevelConfig> _dataMap;
        private readonly List<BlockLevelConfig> _dataList;

        public BlockLevelConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BlockLevelConfig>();
            _dataList = new List<BlockLevelConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BlockLevelConfig _v;
                _v = BlockLevelConfig.DeserializeBlockLevelConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.ID, _v);
            }

            PostInit();
        }

        public Dictionary<int, BlockLevelConfig> DataMap => _dataMap;
        public List<BlockLevelConfig> DataList => _dataList;

        public BlockLevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public BlockLevelConfig Get(int key) => _dataMap[key];
        public BlockLevelConfig this[int key] => _dataMap[key];
        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
