
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BlockLevelConfig : BeanBase
    {
        public BlockLevelConfig(ByteBuf _buf)
        {
            ID = _buf.ReadInt();
            SceneId = _buf.ReadInt();

            PostInit();
        }

        public static BlockLevelConfig DeserializeBlockLevelConfig(ByteBuf _buf)
        {
            return new BlockLevelConfig(_buf);
        }

        public readonly int ID;

        public readonly int SceneId;


        public const int __ID__ = 625481017;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "ID:" + ID + ","
            + "SceneId:" + SceneId + ","
            + "}";
        }

        partial void PostInit();
    }
}
